//
//  SizeProtocol.h
//  DeadCreator
//
//  Created by NamJunHyeon on 2016. 6. 22..
//
//

#pragma once

#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 960

#define GAME_SCREEN_WIDTH (SCREEN_WIDTH * 0.7)
#define GAME_SCREEN_HEIGHT (SCREEN_HEIGHT * 0.7)

#define ICONBAR_HEIGHT 35
#define STATUSBAR_HEIGHT 25
#define WINDOW_PADDING 10

#define PLAYER_SETTING_WIDTH 400
#define PLAYER_SETTING_HEIGHT 250

#define TRIGGER_EDIT_WIDTH 1000
#define TRIGGER_EDIT_HEIGHT 700

#define TRIGGER_PLAYER_HEIGHT 200

#define TRIGGER_COMPONENT_EDIT_WIDTH 1000
#define TRIGGER_COMPONENT_EDIT_HEIGHT 445
