//
//  SizeProtocol.h
//  DeadCreator
//
//  Created by mac on 2016. 6. 22..
//
//

#pragma once

#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 980
#define ICONBAR_HEIGHT 35
#define STATUSBAR_HEIGHT 25
#define WINDOW_PADDING 10

#define TRIGGER_EDIT_WIDTH 800
#define TRIGGER_EDIT_HEIGHT 500

#define TRIGGER_PLAYER_HEIGHT 150

#define TRIGGER_COMPONENT_EDIT_WIDTH 800
#define TRIGGER_COMPONENT_EDIT_HEIGHT 345