// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PACKETCANCELSEARCHGAME_FPACKET_H_
#define FLATBUFFERS_GENERATED_PACKETCANCELSEARCHGAME_FPACKET_H_

#include "flatbuffers.h"

namespace fpacket {

struct PacketCancelSearchGame;

struct PacketCancelSearchGame FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ROOMID = 4
  };
  int32_t roomId() const { return GetField<int32_t>(VT_ROOMID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ROOMID) &&
           verifier.EndTable();
  }
};

struct PacketCancelSearchGameBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_roomId(int32_t roomId) { fbb_.AddElement<int32_t>(PacketCancelSearchGame::VT_ROOMID, roomId, 0); }
  PacketCancelSearchGameBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  PacketCancelSearchGameBuilder &operator=(const PacketCancelSearchGameBuilder &);
  flatbuffers::Offset<PacketCancelSearchGame> Finish() {
    auto o = flatbuffers::Offset<PacketCancelSearchGame>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<PacketCancelSearchGame> CreatePacketCancelSearchGame(flatbuffers::FlatBufferBuilder &_fbb,
   int32_t roomId = 0) {
  PacketCancelSearchGameBuilder builder_(_fbb);
  builder_.add_roomId(roomId);
  return builder_.Finish();
}

inline const fpacket::PacketCancelSearchGame *GetPacketCancelSearchGame(const void *buf) { return flatbuffers::GetRoot<fpacket::PacketCancelSearchGame>(buf); }

inline bool VerifyPacketCancelSearchGameBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fpacket::PacketCancelSearchGame>(); }

inline void FinishPacketCancelSearchGameBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fpacket::PacketCancelSearchGame> root) { fbb.Finish(root); }

}  // namespace fpacket

#endif  // FLATBUFFERS_GENERATED_PACKETCANCELSEARCHGAME_FPACKET_H_
